version: '3.8'
services: 
  backend: 
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db   
      DB_DATABASE: db  postgres
      DB_USERNAME: root  
      DB_PASSWORD: root
    ports:
    - 8000:8000
    volumes:
    - .:/app
    depends_on:
    - db
    networks:
    - app      

  db: 
    image: postgres:11.4-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
    - 15432:5432  
    volumes:
    - .dbdata:/var/lib/postgres  
    networks:
    - app